[colors.bright]
black = "0x444444"
blue = "0x87afd7"
cyan = "0x5fafaf"
green = "0x87af87"
magenta = "0x8787af"
red = "0xff8700"
white = "0xffffff"
yellow = "0xffffaf"

[colors.normal]
black = "0x1c1c1c"
blue = "0x5f87af"
cyan = "0x5f8787"
green = "0x5f875f"
magenta = "0x5f5f87"
red = "0xaf5f5f"
white = "0x6c6c6c"
yellow = "0x87875f"

[colors.primary]
background = "0x262626"
foreground = "0xbcbcbc"
