#!/usr/bin/env sh

FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

while cat "$FIFO"; do :; done | sandbar \
	-font "IBM Plex Mono:12" \
	-active-fg-color "#000000" \
	-active-bg-color "#7aa6da" \
	-inactive-fg-color "#eaeaea" \
	-inactive-bg-color "#000000" \
	-urgent-fg-color "#000000" \
	-urgent-bg-color "#ff3334" \
	-title-fg-color "#000000" \
	-title-bg-color "#7aa6da"
