#!/bin/sh
j4-dmenu-desktop  --dmenu='bemenu -c -i --fork -l 10 -W 0.3 --tf "#ECEFF4" --tb "#4C566A" --fb "#4C566A" --ff "#ECEFF4" --nb "#2E3440" --nf "#ECEFF4" --hb "#ECEFF4" --hf "#2E3440" --ab "#2E3440" --af "#ECEFF4" --cb "#ECEFF4" --fn "Ubuntu Mono 12"'
