#!/bin/sh
j4-dmenu-desktop  --dmenu='bemenu -c -i --single-instance --fork -l 10 -W 0.3 --tf "#bbbbbb" \
    --tb "#222222" \
    --fb "#222222" \
    --ff "#bbbbbb" \
    --nb "#222222" \
    --nf "#bbbbbb" \
    --hb "#005577" \
    --hf "#eeeeee" \
    --ab "#222222" \
    --af "#bbbbbb" \
    --cb "#444444" \
    --fn "IBM Plex Mono 12"'
